### ISSUE TITLE
ee gen-all报错

### ISSUE THREAD

**Issue by Abab-bk** [kaluluosi/GDExcelExporter#4]
```
❯ ee gen-all
gen-WARNING:没有配置文件，将使用内置默认配置
gen-ERROR:未捕获异常
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Applications\Scoop\apps\python\current\Scripts\ee.exe\__main__.py", line 4, in <module>
    from excelexporter.__main__ import main
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\excelexporter\__main__.py", line 3, in <module>
    main()
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\excelexporter\cli.py", line 109, in gen_all
    exporter.gen_all(cwd)
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\excelexporter\exporter.py", line 266, in gen_all
    on_completed()
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\excelexporter\exporter.py", line 53, in on_completed
    completed_gd()
  File "D:\Applications\Scoop\apps\python\current\Lib\site-packages\excelexporter\exporter.py", line 247, in completed_gd
    with open(settings_file_path, "a+", newline="\n", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist\\Settings.gd'
```

**Comment by kaluluosi** [comment]
请使用 ee init 创建配置表目录和生成默认配置Settings.gd再操作

**Comment by Abab-bk** [comment]
已经创建，我使用你的插件正常，命令行就错误😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Hey R You ***@***.***&gt;;
主题: Re: [kaluluosi/GDExcelExporter] ee gen-all报错 (Issue #4)




 
请使用 ee init 创建配置表目录和生成默认配置Settings.gd再操作

**Comment by kaluluosi** [comment]
> 已经创建，我使用你的插件正常，命令行就错误😂
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月18日(周三) 下午3:29 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"Hey R You ***@***.***&gt;; 主题: Re: [kaluluosi/GDExcelExporter] ee gen-all报错 (Issue #4) 请使用 ee init 创建配置表目录和生成默认配置Settings.gd再操作 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你需要cd到settings目录下，或者在settings目录下打开命令行敲ee命令。
