### ISSUE TITLE
使用ee init 命令报错（使用旧版本的ee.exe同样失败）

### ISSUE THREAD

**Issue by TheChinaTeapot** [kaluluosi/GDExcelExporter#43]
请问这个缺少模块的问题如何解决 
ee init
root-CRITICAL:未捕获异常
Traceback (most recent call last):
  File "e:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\python\Scripts\ee.exe\__main__.py", line 4, in <module>
    from gd_excelexporter.cli import cli
  File "e:\python\lib\site-packages\gd_excelexporter\cli.py", line 8, in <module>
    from gd_excelexporter.core.generator import Generator
  File "e:\python\lib\site-packages\gd_excelexporter\core\generator.py", line 11, in <module>
    from gd_excelexporter.config import Configuration
  File "e:\python\lib\site-packages\gd_excelexporter\config.py", line 3, in <module>
    from packaging.version import Version, parse
ModuleNotFoundError: No module named 'packaging'

**Comment by kaluluosi** [comment]
能给出python版本吗？ python3.7以上 packing包是官方内置的包。不清楚你为什么回没有这个包。

**Comment by TheChinaTeapot** [comment]
PS C:\Users\16145\Desktop> python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by kaluluosi** [comment]
我用3.9.10试了下没有问题导出了，没出现你的错误。
建议用pip卸载了重新装。
> pip uninstall gd_excelexporter
> pip install gd_excelexporter
![Uploading Screenshot_20240502_232005_com.aidlux.jpg…]()

**Comment by jinpxx** [comment]
一样的问题。我的Python版本是：
C:\Users\Administrator\Documents\datable>Python
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
出现的报错是：
C:\Users\Administrator\Documents\datable>ee init
root-CRITICAL:未捕获异常
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\ee.exe\__main__.py", line 4, in <module>
    from gd_excelexporter.cli import cli
  File "C:\Program Files\Python312\Lib\site-packages\gd_excelexporter\cli.py", line 8, in <module>
    from gd_excelexporter.core.generator import Generator
  File "C:\Program Files\Python312\Lib\site-packages\gd_excelexporter\core\generator.py", line 11, in <module>
    from gd_excelexporter.config import Configuration
  File "C:\Program Files\Python312\Lib\site-packages\gd_excelexporter\config.py", line 3, in <module>
    from packaging.version import Version, parse
ModuleNotFoundError: No module named 'packaging'
尝试过卸载重装，没有什么变化

**Comment by kaluluosi** [comment]
试一下把这个packaging包装了吧。 3.12 怎么就没了这个内置包了呢。
>pip install packaging

据我查到的信息 3.12 移除了很多内置包。建议用3.8~3.11 这个范围的python版本。
